name: Copy and Update Repository

# This workflow is triggered on pushes to the repository.
on: push

jobs:
  copy-and-push:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository so the workflow can access it
    - uses: actions/checkout@v3

    # Remove existing sitemap.csv in public directory if it exists, and copy the new sitemap.csv
    - name: Update sitemap.csv in public directory
      run: |
        if [ -f public/sitemap.csv ]; then
          echo "sitemap.csv exists in public, replacing..."
          rm public/sitemap.csv
        fi
        cp newsai_script-main/data/sitemap.csv public/sitemap.csv

    # Commit and push if there are changes
    - name: Commit and push changes
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your-email@example.com'
        git add .
        git commit -m "Automated update of public/sitemap.csv" || exit 0  # Prevents the script from failing if there's nothing to commit
        git push
