name: Copy and Update Repository

# This workflow is triggered on pushes to the repository.
on: push

jobs:
  copy-and-push:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository so the workflow can access it
    - uses: actions/checkout@v3

    # Ensure the sitemap.csv file is replaced if it already exists
    - name: Replace sitemap.csv in public directory
      run: |
        if [ -f public/sitemap.csv ]; then
          echo "sitemap.csv exists in public, replacing..."
          rm -f public/sitemap.csv
        fi
        cp newsai_script-main/data/sitemap.csv public/sitemap.csv

    # Display the status of the repo (for debugging purposes)
    - name: Check git status
      run: git status

    # Commit and push if there are changes
    - name: Commit and push changes
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your-email@example.com'
        git add .
        git status  # Optional: For debugging, to see what changes are being detected
        git commit -m "Automated update of public/sitemap.csv" || echo "No changes to commit"
        git push
