name: Update Data

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas requests advertools

      # Run Python scripts
      - name: Run Sitemap Extraction
        run: python site.py
        working-directory: newsai_script-main

      - name: Run YouTube Videos Fetching
        run: python youtube.py
        working-directory: newsai_script-main

      - name: Run Concatenation
        run: python concatenation.py
        working-directory: newsai_script-main

      # Rename old sitemap.csv and update with new one
      - name: Rename existing sitemap.csv to sitemap.old
        run: |
          mv -f newsai_script-main/data/sitemap.old newsai_script-main/data/sitemap.old.bak
          if [ -f newsai_script-main/data/sitemap.csv ]; then
              mv -f newsai_script-main/data/sitemap.csv newsai_script-main/data/sitemap.old
          fi
        working-directory: .

      # Add sitemap.csv to git
      - name: Add sitemap.csv to git
        run: |
          git add newsai_script-main/data/sitemap.old
          git add newsai_script-main/data/sitemap.csv

      # Commit and push sitemap.csv if there are changes
      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Automated update of sitemap.csv and sitemap.old" --allow-empty
          git push origin HEAD:main
