name: Update Data

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the scripts repository
        uses: actions/checkout@v3
        with:
          repository: 'julian-passebecq/newsai_blue_scripts'
          path: 'scripts'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas requests advertools
        working-directory: ./scripts/newsai_script-main

      - name: Run Sitemap Extraction
        run: python ./site.py
        working-directory: ./scripts/newsai_script-main

      - name: Run YouTube Videos Fetching
        run: python ./youtube.py
        working-directory: ./scripts/newsai_script-main

      - name: Run Concatenation
        run: python ./concatenation.py
        working-directory: ./scripts/newsai_script-main

      - name: Check for CSV File Changes
        id: check-csv
        run: |
          echo "Checking if CSV files have changed..."
          if git diff --exit-code ./public/sitemap.csv; then
            echo "No changes in sitemap.csv."
            echo "CSV_CHANGED=false" >> $GITHUB_ENV
          else
            echo "sitemap.csv has changed."
            echo "CSV_CHANGED=true" >> $GITHUB_ENV
          fi
        working-directory: ./scripts

      - name: Commit and Push if Changes
        if: env.CSV_CHANGED == 'true'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add ./public/sitemap.csv
          git commit -m "Automated sitemap.csv update"
          git push origin HEAD:main
        working-directory: ./scripts
