name: Update Data

on:
  schedule:
     - cron: '30 23 * * *'  # Runs at midnight UTC every day
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas requests advertools

      # Delete existing sitemap.csv to avoid duplication issues
      - name: Delete existing sitemap.csv
        run: rm -f newsai_script-main/data/sitemap.csv

      # Run Python scripts which generate a new sitemap.csv
      - name: Run Sitemap Extraction
        run: python site.py
        working-directory: newsai_script-main

      - name: Run YouTube Videos Fetching
        run: python youtube.py
        working-directory: newsai_script-main

      - name: Run Concatenation
        run: python concatenation.py
        working-directory: newsai_script-main

      # Add sitemap.csv to git
      - name: Add sitemap.csv to git
        run: |
          git add newsai_script-main/data/sitemap.csv

      # Commit and push sitemap.csv if it has been updated or created
      - name: Commit and Push sitemap.csv
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Automated update of sitemap.csv" --allow-empty
          git push origin HEAD:main
